search_criteria:
  job_titles:
    - "Financial Analyst"
    - "Reconciliation Analyst"
    - "Data Analyst"
    - "Business Analyst"
    - "Financial Data Analyst"
    - "Financial Reporting"
    - "Treasury Operations"
  locations:
    - location: "Charlottetown, PE"
      date_posted: "last_14_days"
    - location: "Ontario"
      date_posted: "last_3_days"
    - location: "British Columbia"
      date_posted: "last_3_days"
    - location: "Remote"
      date_posted: "last_3_days"
  salary_min: "60000"
  job_types:
    - "full_time"
    - "permanent"

resume_path: resumes

profile: "My name is xxxx. I live in xxxx. Just finished my xxx.
I am looking for a job in xxxx. I have experience in xxxxx. 
I am a quick learner and a team player. I am open to remote work and willing to relocate if necessary. 
I am looking for more entry to mid level roles based on my experience. I still have a lot to learn,"

max_retries: 3

google_sheet:
  sheet_name: "Jobs Sheet"
  credential_path: "keys/gcreds.json"

backend: "gemini"
ollama:
  model: "qwen3:8b"
  temperature: 0.7

openrouter:
  model: "meta-llama/llama-4-scout:free"
  temperature: 0.7

gemini:
  model: "gemma-3-27b-it"
  temperature: 0.7