search_criteria:
  job_titles:
    - "Financial Analyst"
    - "Reconciliation Analyst"
    - "Data Analyst"
    - "Business Analyst"
    - "Financial Data Analyst"
    - "Financial Reporting"
    - "Treasury Operations"
  locations:
    - location: "Charlottetown, PE"
      date_posted: "last_14_days"
    - location: "Ontario"
      date_posted: "last_3_days"
    - location: "British Columbia"
      date_posted: "last_3_days"
    - location: "Remote"
      date_posted: "last_3_days"
  salary_min: "60000"
  job_types:
    - "full_time"
    - "permanent"

resume_path: resumes

profile: "Talented financial analyst with a strong background in data analysis, reconciliation, and financial reporting.
 Proven ability to analyze complex data sets and provide actionable insights. Seeking a challenging position in a 
 dynamic organization where I can leverage my skills and contribute to the success of the team."

max_retries: 3

backend: "ollama"
ollama:
  model: "llama3.1"
  temperature: 0.7