search_criteria:
  job_titles:
#    - "Financial Analyst"
#    - "Reconciliation Analyst"
    - "Data Analyst"
    - "Business Analyst"
    - "Financial Data Analyst"
    - "Financial Reporting"
    - "Treasury Operations"
  locations:
    - "Charlottetown, PE"
    - "Ontario"
    - "British Columbia"
    - "Remote"
  salary_min: "60000"
  date_posted: "last_24_hours"
  keywords_must_include: [
    "financial analyst",
    "reconciliation analyst",
    "data analyst",
    "business analyst",
    "financial data analyst",
    "financial reporting",
    "treasury operations"
  ]
  job_types:
    - "full_time"
    - "permanent"

resume_path: resumes

backend: "ollama"
ollama:
  model: "llama3"
  temperature: 0.7
  max_tokens: 1500
  top_p: 0.9
  frequency_penalty: 0.5
  presence_penalty: 0.5
  stop_sequences:
    - "\n"
    - "END"
    - "STOP"
    - "DONE"
    - "END OF JOB DESCRIPTION"
    - "END OF JOB POSTING"
    - "END OF JOB LISTING"
    - "END OF JOB ADVERTISEMENT"
    - "END OF JOB OPENING"